### ISSUE TITLE
Возможность поиска в статьях

### ISSUE THREAD

**Issue by agurovdev** [Molinos/adminos#10]
@abuhtoyarov Предлагаю добавить для сущности статей/заметок (вообщем текстов) возможность поиска со страницы каталога всех статей.

Критерии приемки:
поиск только по заголовку статьи.

![image](https://user-images.githubusercontent.com/47145464/52121328-5356e480-2630-11e9-8358-945dc869b0e1.png)

**Comment by alsemyonov** [comment]
А ещё надо бы таблицу облагородить — вывести дату публикации, например (может быть, ещё что-то — тогда заголовки к таблице добавить).
